name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install awesome bot
      run: gem install awesome_bot
    - name: Run links validation
      run: awesome_bot **/*.md --allow-dupe --allow-redirect --allow 429 --skip-save-results
